### ISSUE TITLE
Write an example in README file ?

### ISSUE THREAD

**Issue by calag4n** [ismail9k/neomorphism#1]
Hi Ismail, 

I would like to use your library but I don't know how to import a component 😅️.
I'm not familiar with stylus and the docs don't seems really (and above all quickly) helpful.

Could you write an example like import a button in react project maybe ?

Thank you and nice job by the way !

**Comment by ismail9k** [comment]
Hi @calag4n,

I am really glad that you liked my library 😄😄. I plan to expose it as React components until then you can use the lib as an ordinary framework.

- Install the npm package 

```bash
npm i neomorphism
```

- Import styles file

```js
import 'neomorphism';
```

- Use the library HTML markup

```jsx
function App() {
  return (
    <div className="App">
      <button class="button is-md">Standard</button>
    </div>
  );
}
```

**Comment by calag4n** [comment]
Oh, I see.
It's pretty cool, thanks ✌️.
