### ISSUE TITLE
Exposing as react component library

### ISSUE THREAD

**Issue by umutbozdag** [ismail9k/neomorphism#5]
I think i can try to expose this library as a react component library but where can i commit it?

**Comment by umutbozdag** [comment]
Maybe i can create a new branch and commit it to there?

**Comment by ismail9k** [comment]
Hello, @umutbozdag Sure you can. I have created a new branch `feature/react`, which you can create React related PRs to. When eventually the feature is ready, I can merge it to the main branch.
